###########################
# Job
###########################
apiVersion: batch/v1
kind: Job
metadata:
  name: django-job-migrations
spec:
  activeDeadlineSeconds: 120
  template:
    spec:
      containers:
      - name: django-job-migrations
        image: nikolaysysoev/django_dev_image:1.0
        imagePullPolicy: IfNotPresent
        command:
          - python
          - manage.py
          - migrate
        env:
          - name: ALLOWED_HOSTS
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: ALLOWED_HOSTS
          - name: DB_DATABASE
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DB_DATABASE
          - name: DB_USER
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DB_USER
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: DB_PASSWORD
          - name: DB_HOST
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DB_HOST
          - name: DB_PORT
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DB_PORT
          - name: DEBUG
            valueFrom:
              configMapKeyRef:
                name: app-variables
                key: DEBUG
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: app-secrets
                key: SECRET_KEY
      restartPolicy: Never
  backoffLimit: 4